config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'show_user' => 'epicenter#show_user'

  get 'now_following' => 'epicenter#now_following'

  get 'unfollow' => 'epicenter#unfollow'

  get 'following' => 'epicenter#following'

  get 'followers' => 'epicenter#followers'

  get 'tag_tweets' => 'epicenter#tag_tweets'

  resources :tweets
  devise_for :users

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :tweet_tags
	has_many :tweets, through: :tweet_tags
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	belongs_to :user

	has_many :tweet_tags
	has_many :tags, through: :tweet_tags

	validates :message, presence: true
	validates :message, length: {maximum: 140}
end

app/models/tweet_tag.rb
class TweetTag < ActiveRecord::Base
	belongs_to :tweet
	belongs_to :tag
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  has_many :tweets

  validates :username, presence: true, uniqueness: true

  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, :name, :username, :bio, :location, :following, :avatar) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :name, :username, :bio, :location, :following, :avatar) }
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController

	before_filter :authenticate_user!, except: [:show_user]

  def feed
    @tweet = Tweet.new

    @followercount = 0
    User.all.each do |u|
      if u.following.include?(current_user.id)
        @followercount += 1
      end
    end
    
  	@following_tweets = []

  	Tweet.all.each do |tweet|
  		if current_user.following.include?(tweet.user_id) || tweet.user_id == current_user.id
  			@following_tweets.push(tweet)
  		end
  	end
  end

  def show_user
  	@user = User.find(params[:id])
  end

  def now_following
  	current_user.following.push(params[:id].to_i)
  	current_user.save

  	redirect_to :back
  end

  def unfollow
  	current_user.following.delete(params[:id].to_i)
  	current_user.save

  	redirect_to :back
  end

  def followers
    @user = User.find(params[:id])
    @users = []
    User.all.each do |u|
      if u.following.include?(@user.id)
        @users.push(u)
      end
    end
  end

  def following
    @user = User.find(params[:id])
    @users = []
    User.all.each do |u|
      if @user.following.include?(u.id)
        @users.push(u)
      end
    end
  end

  def tag_tweets
    @tag = Tag.find(params[:id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  before_filter :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.create(tweet_params)

    get_tagged(@tweet)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:message, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
	def get_tagged(tweet)
		message_arr = tweet.message.split

    message_arr.each_with_index do |word, index|
      if word[0] == "#"
        if Tag.pluck(:phrase).include?(word)
          tag = Tag.find_by(phrase: word)
        else
          tag = Tag.create(phrase: word)
        end
        TweetTag.create(tweet_id: tweet.id, tag_id: tag.id)
        message_arr[index] = "<a href='/tag_tweets?id=#{tag.id}'>#{word}</a>"
      end
    end

    tweet.update(message: message_arr.join(" "))
	end
end

app/views/epicenter/_currentuser_stats.html.erb
<div class="col-md-4">
	<div class="row">
		<div class="col-md-2">
			<%= image_tag current_user.avatar.url, width: "50" %>
		</div>
		<div class="col-md-10">
			<h3><%= link_to current_user.name, show_user_path(id: current_user.id), class: "no-underline" %></h3>
			<p><%= link_to "@#{current_user.username}", show_user_path(id: current_user.id), class: "no-underline" %></p>
		</div>
	</div>
	<div class="row center-it">
		<div class="col-md-4">
			TWEETS
		</div>
		<div class="col-md-4">
			FOLLOWING
		</div>
		<div class="col-md-4">
			FOLLOWERS
		</div>
	</div>
	<div class="row center-it">
		<div class="col-md-4">
			<%= link_to current_user.tweets.count, show_user_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to current_user.following.count, following_path(id: current_user.id), class: "no-underline" %>
		</div>
		<div class="col-md-4">
			<%= link_to @followercount, followers_path(id: current_user.id), class: "no-underline" %>
		</div>
	</div>
</div>

app/views/epicenter/_userstats.html.erb
<div class="col-md-3">
	<h3><%= link_to @user.name, show_user_path(id: @user.id) %></h3>
	<p><%= link_to "@#{@user.username}", show_user_path(id: @user.id) %></p>
	<p><%= @user.bio %></p>
	<p><i class="fa fa-map-marker"></i> <%= @user.location %></p>
	<p><i class="fa fa-calendar"></i> Joined <%= @user.created_at.strftime("%B %Y") %></p>
	<% if @user.id != current_user.id %>
		<p>
			<% if current_user.following.include?(@user.id) %>
				<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
			<% else %>
				<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
			<% end %>
		</p>
	<% end %>
</div>

app/views/epicenter/feed.html.erb
<div class="row">
	<%= render 'currentuser_stats' %>
	<div class="col-md-7 col-md-offset-1">
		<div class="row new-tweet-area">
			<div class="col-md-1">
				<%#= image_tag current_user.avatar.url, class: "mini-pic" %>
			</div>
			<div class="col-md-11 mtop-6">
				 <%= render 'tweets/form' %>
			</div>
		</div>
		<div class="row">
			<% @following_tweets.each do |tweet| %>
				<div class="col-md-12 tweet-area borderline">
					<p>
						<%= link_to show_user_path(id: tweet.user.id), class: "no-underline" do %>
							<%= tweet.user.name %> <%= "@#{tweet.user.username}" %>
						<% end %>
						&#8226; <%= time_ago_in_words(tweet.created_at) %>
					</p>
					<p><%= tweet.message.html_safe %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/followers.html.erb
<div class="row">
	<%= render 'userstats' %>
	<div class="col-md-8 col-md-offset-1">
		<div class="row">
			<% @users.each do |user| %>
				<div class="col-md-4">
					<div class="well">
						<h3><%= link_to user.name, show_user_path(id: user.id) %></h3>
						<p><%= link_to "@#{user.username}", show_user_path(id: user.id) %></p>
						<p><%= user.bio %></p>
						<p><i class="fa fa-map-marker"></i> <%= user.location %></p>
						<p><i class="fa fa-calendar"></i> Joined <%= user.created_at.strftime("%B %Y") %></p>
						<% if user.id != current_user.id %>
							<p>
								<% if current_user.following.include?(user.id) %>
									<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
								<% else %>
									<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/following.html.erb
<div class="row">
	<%= render 'userstats' %>
	<div class="col-md-8 col-md-offset-1">
		<div class="row">
			<% @users.each do |user| %>
				<div class="col-md-4">
					<div class="well">
						<h3><%= link_to user.name, show_user_path(id: user.id) %></h3>
						<p><%= link_to "@#{user.username}", show_user_path(id: user.id) %></p>
						<p><%= user.bio %></p>
						<p><i class="fa fa-map-marker"></i> <%= user.location %></p>
						<p><i class="fa fa-calendar"></i> Joined <%= user.created_at.strftime("%B %Y") %></p>
						<% if user.id != current_user.id %>
							<p>
								<% if current_user.following.include?(user.id) %>
									<%= link_to "Following", unfollow_path(id: user.id), class: "btn btn-primary", id: "unfollow_btn" %>
								<% else %>
									<%= link_to "Follow", now_following_path(id: user.id), class: "btn btn-primary" %>
								<% end %>
							</p>
						<% end %>
					</div>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/epicenter/show_user.html.erb
<h1>@<%= @user.username %>'s Profile &amp; Tweets</h1>

<p><%= @user.name %></p>
<p><%= @user.location %></p>
<p><%= @user.bio %></p>

<% if user_signed_in? && @user.id != current_user.id %>
	<p>
		<% if current_user.following.include?(@user.id) %>
			<%= link_to "Following", unfollow_path(id: @user.id), class: "btn btn-primary", id: "unfollow_btn" %>
		<% else %>
			<%= link_to "Follow", now_following_path(id: @user.id), class: "btn btn-primary" %>
		<% end %>
	</p>
<% end %>

<% @user.tweets.each do |tweet| %>
	<div>
		@<%= @user.username %>
		<%= tweet.message %>
	</div>
<% end %>

app/views/epicenter/tag_tweets.html.erb
tag_tweets.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterTalentSouth</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-default">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: "navbar-brand" do %>
          <i class="fa fa-home"></i> Home
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to tweets_path do %>
              <i class="fa fa-twitter"></i> All Tweets
            <% end %>
          </li>
        </ul>
        <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Edit Profile", edit_user_registration_path %> </li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        <% end %>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
  <div class="container">
		<%= yield %>
	</div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.text_field :message, placeholder: "What's happening?", class: "form-control" %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.button(class: "btn btn-info") do %>
      <i class="fa fa-pencil-square-o"></i> Tweet
    <% end %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tweets</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.message %></td>
        <td><%= link_to tweet.user.username, show_user_path(id: tweet.user.id) %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @tweet.message.html_safe %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>